//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezzeinventory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMaster
    {
        public AccountMaster()
        {
            this.TaxMasters = new HashSet<TaxMaster>();
        }
    
        public string AccountMasterCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<bool> ProfitLossBalanceSheet { get; set; }
        public string TallyName { get; set; }
        public Nullable<bool> Bank { get; set; }
        public string HsnCode { get; set; }
        public string TaxCode1 { get; set; }
        public string TaxCode2 { get; set; }
        public string TaxCode3 { get; set; }
        public Nullable<decimal> TaxPercentage1 { get; set; }
        public Nullable<decimal> TaxPercentage2 { get; set; }
        public Nullable<decimal> TaxPercentage3 { get; set; }
        public Nullable<decimal> TotalTaxPercentage { get; set; }
        public string TaxDescription1 { get; set; }
        public string TaxDescription2 { get; set; }
        public string TaxDescription3 { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public string CompanyCode { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual ICollection<TaxMaster> TaxMasters { get; set; }
    }
}
