//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezzeinventory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int DistrictId { get; set; }
        public int CityId { get; set; }
        public string PinCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string MobileNumber3 { get; set; }
        public string VatSalesTaxNo { get; set; }
        public Nullable<System.DateTime> FinancialYearFrom { get; set; }
        public Nullable<System.DateTime> FinancialYearTo { get; set; }
        public Nullable<System.DateTime> FinancialYearCurrent { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Website1 { get; set; }
        public string Website2 { get; set; }
        public string GstIdentificationNumber { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAddress { get; set; }
        public string CstNo { get; set; }
        public string LogoLarge { get; set; }
        public string LogoSmall { get; set; }
        public string DataPath { get; set; }
        public string ProductionSerialNumber { get; set; }
        public string ProudctionKey { get; set; }
        public string DataDrive { get; set; }
        public string Cin { get; set; }
        public string BackupDirectory { get; set; }
        public int IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
