//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezzeinventory.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ezzeinventoryEntities : DbContext
    {
        public ezzeinventoryEntities()
            : base("name=ezzeinventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountMaster> AccountMasters { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Excise> Excises { get; set; }
        public DbSet<FinancialYear> FinancialYears { get; set; }
        public DbSet<Godown> Godowns { get; set; }
        public DbSet<HSNCode> HSNCodes { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<PinCode> PinCodes { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<StoreItemType> StoreItemTypes { get; set; }
        public DbSet<StoreSection> StoreSections { get; set; }
        public DbSet<StoreSupplier> StoreSuppliers { get; set; }
        public DbSet<StoreSupply> StoreSupplies { get; set; }
        public DbSet<StoreUnitOfMeasurement> StoreUnitOfMeasurements { get; set; }
        public DbSet<TaxMaster> TaxMasters { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
