//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezzeinventory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSupplier
    {
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> YOB { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> StateCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string PinCodeId { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public string ContactNumber3 { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string MobileNumber3 { get; set; }
        public Nullable<int> CreditDay { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public string AccountMasterCode { get; set; }
        public string Term1 { get; set; }
        public string Term2 { get; set; }
        public string Term3 { get; set; }
        public string Term4 { get; set; }
        public Nullable<int> SupplyCode { get; set; }
        public string TinNumber1 { get; set; }
        public string TinNumber2 { get; set; }
        public string TaxMasterCode { get; set; }
        public string TallyName { get; set; }
        public Nullable<int> DocumentProofId1 { get; set; }
        public Nullable<int> DocumentProofId2 { get; set; }
        public Nullable<int> DocumentProofId3 { get; set; }
        public string SupplierProofNumber1 { get; set; }
        public string SupplierProofNumber2 { get; set; }
        public string SupplierProofNumber3 { get; set; }
        public string SupplierProofCopy1 { get; set; }
        public string SupplierProofCopy2 { get; set; }
        public string SupplierProofCopy3 { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
