//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezzeinventory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        public string TaxCode { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IncludeInStockValuation { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public string AccountMasterCode { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AccountMaster AccountMaster { get; set; }
        public virtual AccountType AccountType { get; set; }
    }
}
